<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>radar_subscriber</name>
  <version>1.0.3</version>
  <description>ROS 2 subscriber for radar_msgs/DetectionList and radar_msgs/ObjectList</description>
  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build-time dependencies -->
  <build_depend>rclcpp</build_depend>
  <build_depend>radar_msgs</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>radar_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>